### PR TITLE
Append the 'data' parameters to the url of GET request

### PR DESCRIPTION
**Pull request by slaw-ik**
Allow to make GET requests with params, when you use methot 'fetch' like:

myCollectionInstance.fetch({data: {some: data, other: param}})

make GET request with URL http://#{model_url}?some=data&other=param

### CODE REVIEW

**Comment by victorquinn** [comment]
Looks good to me, thanks!

**Comment by jgrenat** [comment]
Hi!

Is it possible to make a new release ? When installing via npm, this change is not in the code.

**Comment by victorquinn** [comment]
Oops, my bad, forgot to two that!

Just published the latest to NPM now as 0.4.2

**Comment by jgrenat** [comment]
Thanks, it works! :)

**Comment by slaw-ik** [comment]
Thanks :)

**Pull request merged**
